
-- This is a SQL script to run in the Supabase SQL editor

-- Create the gas_readings table
CREATE TABLE IF NOT EXISTS public.gas_readings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  level NUMERIC NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', now()) NOT NULL
);

-- Set up Row Level Security policies
ALTER TABLE public.gas_readings ENABLE ROW LEVEL SECURITY;

-- Allow all users to read gas_readings
CREATE POLICY "Allow all users to read gas_readings" ON public.gas_readings
  FOR SELECT USING (true);

-- Allow authenticated users to insert into gas_readings
CREATE POLICY "Allow authenticated users to insert into gas_readings" ON public.gas_readings
  FOR INSERT TO authenticated USING (true);

-- Add comments to the table for documentation
COMMENT ON TABLE public.gas_readings IS 'Stores gas level readings from the Gasoo monitoring system';
COMMENT ON COLUMN public.gas_readings.level IS 'The current gas level as a percentage';
