// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nsdmrbhvrbokebggmynx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zZG1yYmh2cmJva2ViZ2dteW54Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2MjAwMjAsImV4cCI6MjA1ODE5NjAyMH0.0vjVQR8GXmeIyaHVQR1gezuabDfXzyP_6d1gdGFPINw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);